### ISSUE TITLE
date and date-time

### ISSUE THREAD

**Issue by BrianKingNOC** [euroargodev/sensor_metadata_json#10]
some fields that are dates have the required format of 
date-time, but some have the format of date
eg in the sensor schema

                "date_creation": {
                    "type": "string",
                    "format": "date-time"
                },

                    },
                    "PREDEPLOYMENT_CALIB_DATE": {
                        "anyOf": [
                            {
                                "type": "string",
                                "format": "date"
                            },

Should we say that all dates are always date-time ?

If the time is unknown, for example a calibration was known to happen on a certain day, then time could be filled with 000000

**Comment by gmaze** [comment]
Starting to work on JSON schema for the Argo VirtualFleet software (https://github.com/euroargodev/VirtualFleet/pull/29 and https://github.com/euroargodev/VirtualFleet_recovery/pull/14), 

I note that ``000000`` would be considered a value, not an absence of information

An ``unknown`` value should be set to ``null`` in JSON ?

Beside, if the format is well indicated as a ``date-time``, in Python this could easily be loaded and considered a [Pandas NaTType](https://pandas.pydata.org/docs/user_guide/missing_data.html#working-with-missing-data)

**Comment by SBS-EREHM** [comment]
This will be resolved in schema version 0.4.0.   All fields with format date are now date-time.

Supporting example code where only a date is vailable propertly encodes the datetime as the date at midnight as RFC 3339 (equiv. ISO8601) format dates, e.g.,   2024-03-19T00:00:00+00:00 or equivalently  2024-03-19T00:00:00:00Z.

Any time-zone aware datetime reader can handle this.

This change touched just about every file and schema. ;-)

**Comment by SBS-EREHM** [comment]
Resolved in dev/0.4.0
