### ISSUE TITLE
convert ISO date-time to Argo 14-char date

### ISSUE THREAD

**Issue by BrianKingNOC** [euroargodev/sensor_metadata_json#11]
I had forgotten that in the json files, date is ISO date

The code to prepare for argo netcdf

make_argo_metanc_from_floatdef_json.m

will need to be modified to convert ISO dates to argo manual 14-char dates YYYYMMDDHHMISS

**Comment by SBS-EREHM** [comment]
I disagree.  Let the DAC convert to this wacky format.  Internation standards should follow ISO / RFC3339 standards for time.

**Comment by BrianKingNOC** [comment]
done

closed
