### ISSUE TITLE
CTD_TEMP_CNDC not in R25

### ISSUE THREAD

**Issue by BrianKingNOC** [euroargodev/sensor_metadata_json#15]
I was writing the covering notes, and looked in R25

I don't see CTD_TEMP_CNDC there, which is a sensor for RBR CTD

Does this mean that the RBR CTD json file shows an error in the schema checker, since it includes that sensor which isn't in R25 ?

**Comment by jeanmichelleconte** [comment]
I agree if we follow the overall logic, there should be no sensor CTD_TEMP_CNDC

The sensor for the parameter "SDN:R03::TEMP_CNDC" should be "SDN:R25::CTD_CNDC" .

**Comment by jeanmichelleconte** [comment]
Ah, just saw the discussion in https://github.com/nvs-vocabs/ArgoVocabs/issues/50

**Comment by SBS-EREHM** [comment]
CTD_TEMP_CNDC is now in R25:
https://vocab.nerc.ac.uk/collection/R25/current/CTD_TEMP_CNDC/
