### ISSUE TITLE
BATTERY_TYPE

### ISSUE THREAD

**Issue by BrianKingNOC** [euroargodev/sensor_metadata_json#18]
@Annie Wong asked whether BATTERY_TYPE should be filled by the DAC/user rather than the platform maker.

Some users open floats and change battery packs. The UK certainly does that with TWR APEXs.

I would suggest that the platform maker fills this field with whatever battery information is relevant to how the float was configured at the factory gate. If a user changes the battery configuration they must notify the DAC to change the BATTERY_TYPE field, because only they know what they did to the float.

For non 'power-users' who don't open a float, the platform maker is the person who knows best what batteries are included, and can write this string in a routine and consistent way. It isn't a controlled string, but will be fairly robust if the platform makers write the strings.

Comments welcome

**Comment by SBS-EREHM** [comment]
Agreed/

**Comment by SBS-EREHM** [comment]
Agreed.
