### ISSUE TITLE
sensor json filenames don't match contents

### ISSUE THREAD

**Issue by BrianKingNOC** [euroargodev/sensor_metadata_json#3]
I found 2 sensor json filenames where the SENSOR_MODEL component didn't match the SENSOR_MODEL inside the file

these were the SBE63, where the correct sensor model is SBE63_OPTODE
and

OCR504_ICSW where the correct sensor model is SATLANTIC_OCR504_ICSW

I have corrected the filenames in the json_sensors directory.

There is now some checking in make_float_json_from_floatdef.m

**Comment by SBS-EREHM** [comment]
Thanks.
