### ISSUE TITLE
R01 and DATA_TYPE in platform json

### ISSUE THREAD

**Issue by BrianKingNOC** [euroargodev/sensor_metadata_json#4]
we're in a bit of a mess over table R01 DATA_TYPE

I think the origin of the mess is my early examples

I had got DATA_TYPE into platform-json, and @Eric has it in the schema, verified against R01
The value in the examples is SDN:R01::META

This is another ID versus alt label issue

The Argo manual says to fill this with eg "Argo meta-data", which is close to but not identical to the preferred label "Argo metadata"

Violetta is investigating whether the API will allow access to preferred or alt labels. If it does, then it would be easy enough to set up a complete set of alt labels that meets all our needs.

Two possible ways out of this issue

1) There is no real need to specify DATA_TYPE in the json. That only really becomes relevant when the netcdf is written. I just thought it was useful to pre-fill it with the correct value. So it could be taken out of platform json schema and examples

2) Keep it in platform json, ask platform makers to fill it with 'Argo meta-data' and accept that it will create warnings until the table labels issue is resolved

**Comment by BrianKingNOC** [comment]
Further to before

The Argo users manual has these options

Argo profile
Argo trajectory
Argo meta-data
Argo technical data
B-Argo profile
B-Argo trajectory (obsolete)
Argo profile merged (obsolete) Argo trajectory merged (obsolete) Argo synthetic profile




note the hyphen in meta-data

The examples I circulated early on did indeed have 'Argo meta-data' as the value. I guess I got that from somewhere.

The present online version of R01 has 'Argo metadata' so that has been 'incorrectly' transcribed from the manual.

Even though no hyphen is cleaner, I'm guessing we have around 17000 GDAC meta.nc files that include the hyphen.

So I guess R01 should introduce the hyphen to reflect the contents of the files and the manual. If R01 remains without the hyphen, all existing files that have it will become non-compliant with the NVS.

And R01 joins R28 as table in which the schema checker will throw out an error using ID checking, until we get altLabel checking

**Comment by SBS-EREHM** [comment]
Hmmmm.  Let's be clear.  The NVS Vocab has three ways to present a term:

1. **ID** as a true URI, e.g., SDN:R01::META
2. Preferred label "prefLabel", e..g., "Argo meta-data"
3. Alternative label "altLabel", in this case "META"

So, in this case, validating against altLabel doesn't solve the problem.  Arggggghhhh!


See:

http://vocab.nerc.ac.uk/collection/R01/current/META/
and
http://vocab.nerc.ac.uk/collection/R01/current/META/?_profile=nvs&_mediatype=application/ld+json

Incomplete JSON-LD snippet for SDN:R01::META here:

```
{
  "@id" : "http://vocab.nerc.ac.uk/collection/R01/current/META/",
  "@type" : "skos:Concept",
  "identifier" : "SDN:R01::META",
  "date" : "2023-10-06 12:38:32.0",
  "dc:identifier" : "SDN:R01::META",
  "authoredOn" : "2023-10-06 12:38:32.0",
  "hasCurrentVersion" : "http://vocab.nerc.ac.uk/collection/R01/current/META/2/",
  "hasVersion" : "http://vocab.nerc.ac.uk/collection/R01/current/META/1/",
  "version" : "2",
  "inDataset" : "http://vocab.nerc.ac.uk/.well-known/void",
  "deprecated" : "false",
  "versionInfo" : "2",
  "altLabel" : "META",
  "definition" : {
    "@language" : "en",
    "@value" : "File containing descriptive information about an Argo float."
  },
  "notation" : "SDN:R01::META",
  "note" : {
    "@language" : "en",
    "@value" : "accepted"
  },
  "prefLabel" : {
    "@language" : "en",
    "@value" : "Argo meta-data"
  },
```

**Comment by BrianKingNOC** [comment]
@SBS-EREHM and I had further discussion of this and concluded that DATA_TYPE doesn't need to be in the platform JSON at all. All this is saying in the meta.nc file is 'This is a metadata file'. That is not something that lives in the platform JSON, or in the aggregated float JSON. It can be added by DACs as they create meta.nc.

**Comment by SBS-EREHM** [comment]
OK.  As of version 0.4.0 of argo.platform.schema.json, DATA_TYPE hsa been removed and any references to table R01.
