### ISSUE TITLE
sensor serial numbers in ECO and MCOMS examples

### ISSUE THREAD

**Issue by BrianKingNOC** [euroargodev/sensor_metadata_json#6]
I noticed an inconsistency in the sensor serial numbers for the FL, BB, CD in the ECO and MCOMS examples

MCOMS 0157 has 3 sensors numbered 0157, which is fine

ECO 3666 has one sensor numbered 3666 and two numbers 0157

Is that a bug in how @Eric made those example files from raw data, or just that placeholders were used, not intended to describe a real ECO ? I'm guessing the latter, but if the ECO file was intended to be a real-life example, it looks like it has a fault.

**Comment by SBS-EREHM** [comment]
That's a bug.  Fixed.  All SN's now 3666.
