### ISSUE TITLE
"created_by" string in make_float_json_from_floatdef.m

### ISSUE THREAD

**Issue by BrianKingNOC** [euroargodev/sensor_metadata_json#9]
make_float_json_from_floatdef.m is presently hardwired with

created_by = 'BAK test';

This is OK for testing but means this tool can't just be adopted by others.

Either each user of the tool needs to edit the created_by line, or we need to find a way of specifying this with some sort of environment parameter passed into the function.

eg we could insist that the dirnames structure passed in must set
dirnames.created_by to be a meaningful non-empty string.

**Comment by SBS-EREHM** [comment]
I changed created_by to use the name of the currently running M-file, available as a MATLAB function:

`created_by = mfilename`
